//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::{
    client::Entity as Client, download_request::Entity as DownloadRequest,
    download_result::Entity as DownloadResult,
};
